sudo: required
dist: trusty

language: cpp

branches:
  only:
    - dev

before_install:
  - sudo apt-get -qq update

install:
  - git clone https://github.com/nerdvegas/rez.git
  - cd rez
  - python ./install.py -v /tmp/rez
  - cd ..
  - export PATH=/tmp/rez/bin/rez:$PATH
  - mkdir -p /home/travis/packages
  - rez-bind platform
  - rez-bind arch
  - rez-bind os
  - rez-bind python

script:
  rez-build -i

