sudo: required
dist: trusty

language: cpp

branches:
  only:
    - dev

before_install:
  - sudo apt-get -qq update
  - git clone https://github.com/nerdvegas/rez.git
  - cd rez
  - python ./install.py -v ../rez

install:
  rez-build

