sudo: required
dist: trusty

language: cpp

branches:
  only:
    - dev

env:
  - VERSION=2.7.9
  - VERSION=2.7.13

before_install:
  - sudo apt-get -qq update

install:
  - git clone https://github.com/nerdvegas/rez.git
  - cd rez
  - python ./install.py -v /tmp/rez
  - cd ..
  - export PATH=/tmp/rez/bin/rez:$PATH
  - mkdir -p /home/travis/packages
  - rez-bind platform
  - rez-bind arch
  - rez-bind os
  - rez-bind python

script:
  - sed -i s/version.*=.*/version=\"${VERSION}\"/ package.py
  - rez-build -i

